# Generated by Django 4.2.7 on 2024-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_trialrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
