# Generated by Django 4.2.7 on 2024-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-25 15:11:29.330655'),
            preserve_default=False,
        ),
    ]
